name: Build Dev Image

on:
  push:
    branches: ["dev"]

jobs:
  build:
    if: github.actor != 'github-actions'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set image tag from commit SHA
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "IMAGE_TAG=v3-$SHORT_SHA" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/dev-app:$IMAGE_TAG .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/dev-app:$IMAGE_TAG

      - name: Update rollout image tag
        run: |
          sed -i "s|\(image: .*dev-app:\).*|\1$IMAGE_TAG|" deployments/dev/dev-rollout.yaml
      - name: Commit rollout update
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add deployments/dev/dev-rollout.yaml
          git commit -m "Deploy dev-app $IMAGE_TAG" || echo "No changes to commit"
          git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
          git push origin HEAD:dev
